packages:
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  esbuild: true
  sharp: true
  svelte-preprocess: true
minimumReleaseAgeExclude:
  - '@lucide/svelte@1.23.0'
  - '@lucide/vue@1.23.0'
  - vite@8.1.3
